### PR TITLE
Functions - Optimized MarkerLoop and renamed it to markerHandler

### LINKED ISSUE #2: Functions - Artillery Marker Distance reported wrongly if marker text is modified
"changing arty marker name or moving it changes distance (like arty1 to arty1 smoke), same when deleting marker on the map, and replacing it"

### LINKED ISSUE #3: Functions - Only the latest GPS Marker is active
"only 1 gps marker active at a time (newest one), moving them deactives it, also deactivates after a few minutes"

### PR DESCRIPTION
**Pull request by Tapawingo**
**When merged this pull request will:**
- Fix https://github.com/RemoteControlledArty/RemoteControlledArtillery/issues/2
- Fix https://github.com/RemoteControlledArty/RemoteControlledArtillery/issues/3
- Optimize code (Network and hardware optimizations)
- Rename `RC_MarkerLoop` to `RC_MarkerHandler`
- Add `fn_preInit.sqf` for GVAR declarations

### CODE REVIEW

**Comment by Tapawingo** [comment]
*Requires testing in Singleplayer, Self-Hosted Multiplayer and Dedicated environments before merge.*

- [X] Singleplayer
- [x] Self-Hosted Multiplayer
- [x] Dedicated

**Comment by realfluffyuwu** [comment]
Looks much better than my implementation, I'm not sure why I didn't use mission event handlers from the beginning, I probably ran into some Stupid Arma Problem and brute forced my way around it

**Review by realfluffyuwu — APPROVED** [review]
It will need Testing to make sure no fuckery arises from Locality issues but otherwise I see no issues with it

**Comment by Tapawingo** [comment]
> It will need Testing to make sure no fuckery arises from Locality issues but otherwise I see no issues with it

I don't think locality will be a issue as the resulting array is streamed to all clients on the network. I believe general functionality is where issues are more likely to arise as I have not taken the time to read through all of your code. There is a high likelihood I've accidentally removed intended functionality without realizing it. 

That's not to say locality shouldn't be tested, rather, I don't think it should be the priority. Also I would've tested it myself, however,  I'm a full-time university student and I got a lot of work this week so I just haven't had the time 😅

**Comment by Tapawingo** [comment]
It's now been tested by both me and @RemoteControlledArty in singleplayer and works as intended. It's ready to be merged. Before the next release though I recommend doing a full test in a dedicated environment making sure that everything works.

**Pull request merged**
